export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const GET_PROYECTOS = 'GET_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const ERROR_FORMULARIO = 'ERROR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';