//Proyecto context
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const GET_PROYECTOS = 'GET_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const ERROR_FORMULARIO = 'ERROR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';

//Tarea context
export const GET_TAREAS_PROYECTO = 'GET_TAREAS_PROYECTO';
export const ERROR_TAREA = 'ERROR_TAREA';
export const NUEVA_TAREA_PROYECTO = 'NUEVA_TAREA_PROYECTO';
export const ELIMINAR_TAREA_PROYECTO = 'ELIMINAR_TAREA_PROYECTO';
export const TAREA_PROYECTO_ACTUAL = 'TAREA_PROYECTO_ACTUAL';
export const ACTUALIZAR_TAREA_PROYECTO = 'ACTUALIZAR_TAREA_PROYECTO';
export const TAREA_ERROR = 'TAREA_ERROR';

//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Autenticacion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';